//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace WindowsFormsApplication1
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DictCnEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DictCnEntities”部分中的连接字符串初始化新 DictCnEntities 对象。
        /// </summary>
        public DictCnEntities() : base("name=DictCnEntities", "DictCnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DictCnEntities 对象。
        /// </summary>
        public DictCnEntities(string connectionString) : base(connectionString, "DictCnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DictCnEntities 对象。
        /// </summary>
        public DictCnEntities(EntityConnection connection) : base(connection, "DictCnEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<分类> 分类集
        {
            get
            {
                if ((_分类集 == null))
                {
                    _分类集 = base.CreateObjectSet<分类>("分类集");
                }
                return _分类集;
            }
        }
        private ObjectSet<分类> _分类集;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 分类集 EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTo分类集(分类 分类)
        {
            base.AddObject("分类集", 分类);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DictCnModel", Name="分类")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class 分类 : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 分类 对象。
        /// </summary>
        /// <param name="id">ID 属性的初始值。</param>
        /// <param name="名称">名称 属性的初始值。</param>
        /// <param name="地址">地址 属性的初始值。</param>
        public static 分类 Create分类(global::System.Int32 id, global::System.String 名称, global::System.String 地址)
        {
            分类 分类 = new 分类();
            分类.ID = id;
            分类.名称 = 名称;
            分类.地址 = 地址;
            return 分类;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 名称
        {
            get
            {
                return _名称;
            }
            set
            {
                On名称Changing(value);
                ReportPropertyChanging("名称");
                _名称 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("名称");
                On名称Changed();
            }
        }
        private global::System.String _名称;
        partial void On名称Changing(global::System.String value);
        partial void On名称Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String 地址
        {
            get
            {
                return _地址;
            }
            set
            {
                On地址Changing(value);
                ReportPropertyChanging("地址");
                _地址 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("地址");
                On地址Changed();
            }
        }
        private global::System.String _地址;
        partial void On地址Changing(global::System.String value);
        partial void On地址Changed();

        #endregion
    
    }

    #endregion
    
}
